name: CD Pipeline for IEEE analysis method for Chromamon

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull paulopossatto/chromamon-ieee-analysis:latest

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Verify Deployment
        run: |
          curl --fail http://localhost:8080/health || exit 1
