name: CI/CD Pipeline for IEEE Analysis Method for Chromamon

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-and-docker:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: chroma_user
          POSTGRES_PASSWORD: chroma_pass
          POSTGRES_DB: chroma_db
        options: >-
          --health-cmd="pg_isready -U chroma_user -d chroma_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            nc -z localhost 5433 && echo "PostgreSQL is up" && break || echo "Waiting for PostgreSQL..."
            sleep 5
          done

      - name: Create Schema in PostgreSQL
        run: |
          until pg_isready -h localhost -p 5433 -U chroma_user; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run Tests
        run: mvn test

      - name: List target directory
        run: ls -al target

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/chromamon-ieee-analysis:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/chromamon-ieee-analysis:latest